/**
 * "Initialize Jumperless Project" command.
 *
 * Sets up a workspace so the Jumperless firmware's globally-injected API
 * (dac_set, read_probe, oled_print, TOP_RAIL, ...) is recognized by
 * Pylance / Pyright with full autocomplete + types and NO per-file imports —
 * mirroring how the firmware runs every script after `from jumperless import *`.
 *
 * It writes into <workspace>/typings/:
 *   - jumperless.pyi : the typed stub bundled with the extension (synced from
 *                      JumperlOS via `npm run sync-stubs`); falls back to a stub
 *                      generated from the API reference if the bundle is missing
 *   - builtins.pyi   : the active language server's stdlib builtins with the
 *                      Jumperless globals layered on top, so bare names resolve
 *                      everywhere (the only way Pyright exposes "global" names)
 *   - time.pyi       : MicroPython time extras (ticks_ms/sleep_ms/...)
 * plus pyrightconfig.json (+ best-effort .vscode/settings.json).
 *
 * Each piece is individually toggleable via the `jumperless.setup.*` settings,
 * so users can keep "just the Python stubs" and skip the rest.
 */

import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';
import * as os from 'os';
import { getApiData, loadApiData, getConstants, ApiRefData } from '../language/apiData';
import { getConfig } from '../utils';

/** Read a `jumperless.setup.<key>` boolean toggle (defaults to true). */
function setupEnabled(key: string): boolean {
    const v = getConfig<boolean>(`setup.${key}`);
    return v === undefined ? true : v;
}

const GENERATED_HEADER =
    '# AUTO-GENERATED by JumperIDE ("Initialize Jumperless Project").\n' +
    '# Edits will be overwritten. Re-run the command to regenerate.\n';

export function registerInitProject(context: vscode.ExtensionContext): void {
    context.subscriptions.push(
        vscode.commands.registerCommand('jumperless.initProject', () => runInitProject(context)),
        vscode.commands.registerCommand('jumperless.initGlobal', () => runInitGlobal(context)),
    );
}

/** Where global (all-workspaces) stubs live. */
function globalTypingsDir(): string {
    return path.join(os.homedir(), '.jumperless', 'typings');
}

interface GlobalResult { did: string[]; wantGlobal: boolean; globalRecognition: boolean; }

/** Write the global stubs and point user-level Python settings at them. */
async function applyGlobalSetup(context: vscode.ExtensionContext): Promise<GlobalResult> {
    const dir = globalTypingsDir();
    fs.mkdirSync(dir, { recursive: true });

    const did: string[] = [];
    if (setupEnabled('jumperlessStub')) {
        writeApiStubs(context, dir);
        did.push('jumperless.pyi');
    }
    if (setupEnabled('includeTimeStub')) {
        fs.writeFileSync(path.join(dir, 'time.pyi'), TIME_STUB, 'utf-8');
        did.push('time.pyi');
    }

    const wantGlobal = setupEnabled('globalRecognition');
    let globalRecognition = false;
    if (wantGlobal) {
        globalRecognition = writeGlobalBuiltins(dir);
        if (globalRecognition) { did.push('builtins.pyi (global API)'); }
    } else {
        tryUnlink(path.join(dir, 'builtins.pyi'));
    }

    // Point user-level (all-workspaces) settings at the global stub folder.
    const cfg = vscode.workspace.getConfiguration();
    const G = vscode.ConfigurationTarget.Global;
    const extra = cfg.inspect<string[]>('python.analysis.extraPaths')?.globalValue ?? [];
    if (!extra.includes(dir)) {
        await cfg.update('python.analysis.extraPaths', [...extra, dir], G);
    }
    if (wantGlobal && globalRecognition) {
        // The builtins shim only takes effect when it's on the stub path.
        await cfg.update('python.analysis.stubPath', dir, G);
    }
    const sev = {
        ...(cfg.inspect<Record<string, string>>('python.analysis.diagnosticSeverityOverrides')?.globalValue ?? {}),
        reportMissingModuleSource: 'none',
        reportMissingImports: 'none',
        ...(wantGlobal && !globalRecognition ? { reportUndefinedVariable: 'none' } : {}),
    };
    await cfg.update('python.analysis.diagnosticSeverityOverrides', sev, G);

    return { did, wantGlobal, globalRecognition };
}

function globalDetail(r: GlobalResult): string {
    if (!r.wantGlobal) { return 'Use `from jumperless import *` for autocomplete.'; }
    if (r.globalRecognition) { return 'The Jumperless API now resolves globally in every workspace — no imports needed.'; }
    return "Couldn't find the language server's builtins, so undefined-name warnings were disabled instead.";
}

/**
 * Set up Jumperless autocomplete for ALL workspaces by writing the stubs to a
 * stable home-dir folder and pointing the user-level Python analysis settings
 * there. Because Pyright only exposes "global" names via the stub path, this
 * sets `python.analysis.stubPath` at the user level — projects that ship their
 * own pyrightconfig.json / stubPath are unaffected.
 */
export async function runInitGlobal(context: vscode.ExtensionContext): Promise<void> {
    const dir = globalTypingsDir();
    const ok = await vscode.window.showWarningMessage(
        'Set up Jumperless autocomplete for ALL workspaces?',
        {
            modal: true,
            detail:
                `Stubs will be written to ${dir} and your user settings will point ` +
                'python.analysis.stubPath + extraPaths there, so the Jumperless API resolves ' +
                'with no imports in every project. Projects with their own pyrightconfig.json ' +
                'are unaffected. Re-run "Initialize Jumperless Project" in a folder to override locally.',
        },
        'Set Up Globally',
    );
    if (ok !== 'Set Up Globally') { return; }

    if (setupEnabled('recommendExtensions')) {
        await ensureRecommendedExtensions();
    }

    const r = await applyGlobalSetup(context);
    if (r.did.length === 0) {
        vscode.window.showInformationMessage('Nothing to set up — enable some jumperless.setup.* options first.');
        return;
    }
    const choice = await vscode.window.showInformationMessage(
        `Jumperless autocomplete set up globally (${r.did.join(', ')}). ${globalDetail(r)}`,
        'Reload Window',
    );
    if (choice === 'Reload Window') {
        vscode.commands.executeCommand('workbench.action.reloadWindow');
    }
}

/**
 * On activation, set up global Jumperless autocomplete once (no prompt) so it
 * "just works" everywhere — including files opened from the device. Gated by
 * the `jumperless.setup.autoSetUpGlobally` toggle and a one-time flag.
 */
export async function autoEnsureGlobalSetup(context: vscode.ExtensionContext): Promise<void> {
    if (!setupEnabled('autoSetUpGlobally') || !setupEnabled('jumperlessStub')) { return; }

    const dir = globalTypingsDir();
    const cfg = vscode.workspace.getConfiguration();
    const stubPathGlobal = cfg.inspect<string>('python.analysis.stubPath')?.globalValue;
    const wantGlobal = setupEnabled('globalRecognition');
    const configured = fs.existsSync(path.join(dir, 'jumperless.pyi')) &&
        (!wantGlobal || stubPathGlobal === dir);

    if (configured) {
        // Keep the stubs fresh (cheap), but don't nag.
        await applyGlobalSetup(context);
        return;
    }
    if (context.globalState.get<boolean>('jumperless.autoGlobalDone')) { return; }

    const r = await applyGlobalSetup(context);
    context.globalState.update('jumperless.autoGlobalDone', true);
    if (r.did.length === 0) { return; }

    const choice = await vscode.window.showInformationMessage(
        `JumperIDE set up Jumperless autocomplete for all workspaces. ${globalDetail(r)}`,
        'Reload Window', 'Settings',
    );
    if (choice === 'Reload Window') {
        vscode.commands.executeCommand('workbench.action.reloadWindow');
    } else if (choice === 'Settings') {
        vscode.commands.executeCommand('workbench.action.openSettings', 'jumperless.setup');
    }
}

/**
 * Files opened from the device are loose `file://` working copies outside any
 * workspace, so they only pick up Jumperless autocomplete from user-level
 * settings. Make sure the global stubs exist (prompting once). Called when a
 * device file is opened locally.
 */
export async function ensureGlobalStubsForLooseFiles(context: vscode.ExtensionContext): Promise<void> {
    if (!setupEnabled('jumperlessStub')) { return; }
    const dir = globalTypingsDir();
    const cfg = vscode.workspace.getConfiguration();
    const stubPathGlobal = cfg.inspect<string>('python.analysis.stubPath')?.globalValue;
    const wantGlobal = setupEnabled('globalRecognition');

    // Already wired up? Just refresh the stub files quietly and move on.
    const configured = fs.existsSync(path.join(dir, 'jumperless.pyi')) &&
        (!wantGlobal || stubPathGlobal === dir);
    if (configured) {
        await applyGlobalSetup(context);
        return;
    }

    if (context.globalState.get<boolean>('jumperless.deviceAutocompleteDeclined')) { return; }
    const ans = await vscode.window.showInformationMessage(
        'Enable Jumperless autocomplete for files opened from the device? ' +
        'This sets up global stubs (~/.jumperless/typings) so device files resolve the API with no imports.',
        'Enable', 'Not Now', "Don't Ask Again",
    );
    if (ans === "Don't Ask Again") {
        context.globalState.update('jumperless.deviceAutocompleteDeclined', true);
        return;
    }
    if (ans !== 'Enable') { return; }

    if (setupEnabled('recommendExtensions')) {
        await ensureRecommendedExtensions();
    }
    const r = await applyGlobalSetup(context);
    const choice = await vscode.window.showInformationMessage(
        `Jumperless autocomplete enabled for device files (${r.did.join(', ')}). ${globalDetail(r)}`,
        'Reload Window',
    );
    if (choice === 'Reload Window') {
        vscode.commands.executeCommand('workbench.action.reloadWindow');
    }
}

export async function runInitProject(context: vscode.ExtensionContext): Promise<void> {
    const folders = vscode.workspace.workspaceFolders;
    if (!folders || folders.length === 0) {
        vscode.window.showWarningMessage('Open a workspace folder first, then run "Jumperless: Initialize Jumperless Project".');
        return;
    }

    // Let the user pick which folder when there are several (multi-root).
    let root = folders[0].uri.fsPath;
    if (folders.length > 1) {
        const pick = await vscode.window.showQuickPick(
            folders.map((f) => ({ label: f.name, description: f.uri.fsPath, fsPath: f.uri.fsPath })),
            { title: 'Initialize Jumperless project in which folder?' },
        );
        if (!pick) { return; }
        root = pick.fsPath;
    }

    if (setupEnabled('recommendExtensions')) {
        await ensureRecommendedExtensions();
    }

    const typingsDir = path.join(root, 'typings');
    fs.mkdirSync(typingsDir, { recursive: true });

    const did: string[] = [];

    // 1) jumperless.pyi + oledgui.pyi — the typed API stubs (the core piece).
    if (setupEnabled('jumperlessStub')) {
        writeApiStubs(context, typingsDir);
        did.push('jumperless.pyi');
    }

    // 2) time.pyi — MicroPython timing extras.
    if (setupEnabled('includeTimeStub')) {
        fs.writeFileSync(path.join(typingsDir, 'time.pyi'), TIME_STUB, 'utf-8');
        did.push('time.pyi');
    }

    // 3) builtins.pyi — make the firmware globals resolve everywhere (no imports).
    const wantGlobal = setupEnabled('globalRecognition');
    let globalRecognition = false;
    if (wantGlobal) {
        globalRecognition = writeGlobalBuiltins(typingsDir);
        if (globalRecognition) { did.push('builtins.pyi (global API)'); }
    } else {
        // Toggled off: drop any builtins shim a previous run left behind.
        tryUnlink(path.join(typingsDir, 'builtins.pyi'));
    }

    // 4) Config: pyrightconfig.json (authoritative) + best-effort settings.json.
    //    Suppress undefined-name warnings only when the user *wanted* global
    //    recognition but we couldn't build the shim.
    const suppressUndefined = wantGlobal && !globalRecognition;
    if (setupEnabled('writeProjectConfig')) {
        writePyrightConfig(root, suppressUndefined);
        writeVscodeSettings(root, suppressUndefined);
        did.push('pyrightconfig.json');
    }

    let detail: string;
    if (!wantGlobal) {
        detail = 'Use `from jumperless import *` at the top of scripts for autocomplete.';
    } else if (globalRecognition) {
        detail = 'The Jumperless API is now recognized globally — no imports needed.';
    } else {
        detail = "Couldn't find the language server's builtins, so undefined-name warnings were disabled instead. Autocomplete works after `from jumperless import *`.";
    }
    if (did.length === 0) {
        vscode.window.showInformationMessage(
            'Nothing to set up — all jumperless.setup.* options are disabled. Enable some in Settings.',
        );
        return;
    }
    const choice = await vscode.window.showInformationMessage(
        `Jumperless project initialized (${did.join(', ')}). ${detail}`,
        'Reload Window',
    );
    if (choice === 'Reload Window') {
        vscode.commands.executeCommand('workbench.action.reloadWindow');
    }
}

/**
 * Copy the bundled typed stubs (jumperless + oledgui, synced from JumperlOS)
 * into `dir`. Falls back to generating jumperless.pyi from the API reference if
 * the bundle is missing. oledgui is bundle-only (skipped if absent).
 */
function writeApiStubs(context: vscode.ExtensionContext, dir: string): void {
    const jl = path.join(context.extensionPath, 'stubs', 'jumperless.pyi');
    const jlDst = path.join(dir, 'jumperless.pyi');
    let copied = false;
    if (fs.existsSync(jl)) {
        try { fs.copyFileSync(jl, jlDst); copied = true; } catch { /* fall through */ }
    }
    if (!copied) {
        const api = getApiData() ?? loadApiData(context.extensionPath);
        fs.writeFileSync(jlDst, generateStub(api), 'utf-8');
    }

    const oled = path.join(context.extensionPath, 'stubs', 'oledgui.pyi');
    if (fs.existsSync(oled)) {
        try { fs.copyFileSync(oled, path.join(dir, 'oledgui.pyi')); } catch { /* optional */ }
    }
}

function tryUnlink(file: string): void {
    try {
        if (fs.existsSync(file)) { fs.unlinkSync(file); }
    } catch {
        /* best effort */
    }
}

/**
 * Offer setup once per workspace: if there are Python files but no
 * typings/jumperless.pyi yet, gently suggest running init. Non-naggy — we
 * remember the answer in workspaceState so we never ask twice.
 */
export async function maybeOfferSetup(context: vscode.ExtensionContext): Promise<void> {
    const folders = vscode.workspace.workspaceFolders;
    if (!folders || folders.length === 0) { return; }
    // Global auto-setup (default) covers every workspace, so don't also nag per-folder.
    if (setupEnabled('autoSetUpGlobally')) { return; }
    if (!setupEnabled('offerOnFirstOpen')) { return; }
    if (context.workspaceState.get<boolean>('jumperless.setupOffered')) { return; }

    const alreadySetUp = folders.some((f) =>
        fs.existsSync(path.join(f.uri.fsPath, 'typings', 'jumperless.pyi')));
    if (alreadySetUp) { return; }

    const py = await vscode.workspace.findFiles('**/*.{py,jython}', '**/node_modules/**', 1);
    if (py.length === 0) { return; }

    context.workspaceState.update('jumperless.setupOffered', true);
    const ans = await vscode.window.showInformationMessage(
        'Set up Jumperless autocomplete for this folder? Adds typed stubs so the API resolves with no imports.',
        'Set Up', 'Not Now',
    );
    if (ans === 'Set Up') {
        await runInitProject(context);
    }
}

/** Prompt to install Python + Pylance if missing (skippable). */
async function ensureRecommendedExtensions(): Promise<void> {
    const haveAnalyzer =
        vscode.extensions.getExtension('ms-python.vscode-pylance') ||
        vscode.extensions.getExtension('anysphere.cursorpyright') ||
        vscode.extensions.getExtension('detachhead.basedpyright');
    if (haveAnalyzer) { return; }

    const wanted = [
        { id: 'ms-python.python', name: 'Python' },
        { id: 'ms-python.vscode-pylance', name: 'Pylance' },
    ];
    for (const ext of wanted) {
        if (vscode.extensions.getExtension(ext.id)) { continue; }
        const ans = await vscode.window.showInformationMessage(
            `The ${ext.name} extension is recommended for Jumperless autocomplete. Install it?`,
            'Install', 'Skip',
        );
        if (ans === 'Install') {
            try {
                await vscode.commands.executeCommand('workbench.extensions.installExtension', ext.id);
            } catch {
                /* user can install manually */
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Stub generation
// ---------------------------------------------------------------------------

/** Build a valid, typed `jumperless.pyi` from the API reference + constants. */
export function generateStub(api: ApiRefData | null): string {
    const headings = api?.headings ?? [];
    const descriptions = api?.descriptions ?? {};

    const lines: string[] = [
        GENERATED_HEADER.trimEnd(),
        '"""Jumperless MicroPython API — type stubs for editor autocomplete."""',
        'from typing import Any',
        '',
    ];

    const emitted = new Set<string>();
    for (const heading of headings) {
        const fn = parseHeading(heading);
        if (!fn || emitted.has(fn.name)) { continue; }
        emitted.add(fn.name);

        const doc = descriptions[normalize(fn.name)];
        lines.push(`def ${fn.name}(${fn.params}) -> Any:`);
        if (doc) {
            lines.push(`    """${escapeDocstring(doc)}"""`);
        }
        lines.push('    ...');
        lines.push('');
    }

    // Constants / pin names / filesystem objects, so bare names resolve.
    const constants = getConstants();
    if (constants.length) {
        lines.push('# Constants and pin aliases injected by the firmware.');
        for (const c of constants) {
            if (isValidIdentifier(c) && !emitted.has(c)) {
                emitted.add(c);
                lines.push(`${c}: Any`);
            }
        }
        lines.push('');
    }

    // Anything not explicitly listed (future API, dotted helpers) still resolves.
    lines.push('def __getattr__(name: str) -> Any: ...');
    lines.push('');
    return lines.join('\n');
}

interface ParsedFn { name: string; params: string; }

/** Parse an API heading like `connect(a, b, [dup=-1])` into a valid Python def. */
function parseHeading(heading: string): ParsedFn | null {
    const open = heading.indexOf('(');
    const close = heading.lastIndexOf(')');
    if (open <= 0 || close < open) { return null; }

    const name = heading.slice(0, open).trim();
    // Skip object methods / attributes (jfs.*, file.*, pin.value): they're
    // reached through objects typed as Any, not module-level functions.
    if (!isValidIdentifier(name)) { return null; }

    const rawArgs = heading.slice(open + 1, close).trim();
    if (rawArgs === '') { return { name, params: '' }; }

    const params: string[] = [];
    let seenOptional = false;
    for (let token of rawArgs.split(',')) {
        token = token.trim();
        if (!token) { continue; }

        // `[name=default]` / `[name]` → optional argument.
        const optional = token.startsWith('[') && token.endsWith(']');
        if (optional) { token = token.slice(1, -1).trim(); }

        if (token.startsWith('*')) {
            // *args / **kwargs — pass through, don't force defaults after.
            params.push(token);
            continue;
        }

        const hasDefault = token.includes('=');
        if (optional || hasDefault) {
            seenOptional = true;
            params.push(hasDefault ? token : `${token}=...`);
        } else if (seenOptional) {
            // Python forbids a required arg after an optional one — make it optional.
            params.push(`${token}=...`);
        } else {
            params.push(token);
        }
    }
    return { name, params: params.join(', ') };
}

function normalize(name: string): string {
    return name.toLowerCase().replace(/-/g, '_');
}

function isValidIdentifier(s: string): boolean {
    return /^[A-Za-z_][A-Za-z0-9_]*$/.test(s);
}

function escapeDocstring(doc: string): string {
    return doc.replace(/\\/g, '\\\\').replace(/"""/g, '\\"\\"\\"').replace(/\r?\n/g, ' ').trim();
}

// ---------------------------------------------------------------------------
// Global recognition (builtins shim)
// ---------------------------------------------------------------------------

/**
 * Write typings/builtins.pyi = (active language server's stdlib builtins) +
 * the Jumperless globals layered on top. Returns true on success.
 *
 * Pyright/Pylance has no "extend builtins" setting — a stub-path builtins.pyi
 * fully *replaces* the bundled one. So we copy the server's own builtins (kept
 * version-matched) and prepend the firmware globals. This makes bare names
 * resolve project-wide while keeping the full standard library intact.
 */
function writeGlobalBuiltins(typingsDir: string): boolean {
    const stdlibBuiltins = findStdlibBuiltins();
    if (!stdlibBuiltins) { return false; }

    let body: string;
    try {
        body = fs.readFileSync(stdlibBuiltins, 'utf-8');
    } catch {
        return false;
    }

    const preamble =
        GENERATED_HEADER +
        '# typeshed `builtins` (copied from the active language server) + the\n' +
        '# Jumperless firmware globals, so scripts resolve API names without imports.\n' +
        'from jumperless import *\n' +
        '\n' +
        '# The firmware also imports these into the script namespace at startup.\n' +
        'import time as time\n' +
        'import os as os\n' +
        'import math as math\n' +
        'import gc as gc\n' +
        '\n' +
        '# ---- begin vendored typeshed builtins ----\n';

    fs.writeFileSync(path.join(typingsDir, 'builtins.pyi'), preamble + body, 'utf-8');
    return true;
}

/** Find the bundled stdlib/builtins.pyi of whichever Python analyzer is active. */
function findStdlibBuiltins(): string | null {
    const ids = [
        'anysphere.cursorpyright',     // Cursor
        'ms-python.vscode-pylance',    // VSCode
        'detachhead.basedpyright',     // basedpyright users
    ];
    const rel = path.join('dist', 'typeshed-fallback', 'stdlib', 'builtins.pyi');
    for (const id of ids) {
        const ext = vscode.extensions.getExtension(id);
        if (!ext) { continue; }
        const p = path.join(ext.extensionPath, rel);
        if (fs.existsSync(p)) { return p; }
    }
    return null;
}

const TIME_STUB =
    GENERATED_HEADER +
    '"""MicroPython `time` extras for editor tooling (not uploaded to the board).\n' +
    '\n' +
    "CPython's `time` stub lacks ticks_*/sleep_ms/sleep_us. This shadows it with\n" +
    'the MicroPython surface; the __getattr__ fallback keeps the rest as Any."""\n' +
    '\n' +
    'from typing import Any\n' +
    '\n' +
    'def sleep(seconds: float) -> None: ...\n' +
    'def sleep_ms(ms: int) -> None: ...\n' +
    'def sleep_us(us: int) -> None: ...\n' +
    'def ticks_ms() -> int: ...\n' +
    'def ticks_us() -> int: ...\n' +
    'def ticks_cpu() -> int: ...\n' +
    'def ticks_add(ticks: int, delta: int) -> int: ...\n' +
    'def ticks_diff(ticks1: int, ticks2: int) -> int: ...\n' +
    '\n' +
    'def __getattr__(name: str) -> Any: ...\n';

// ---------------------------------------------------------------------------
// Config files
// ---------------------------------------------------------------------------

function writePyrightConfig(root: string, suppressUndefined: boolean): void {
    const file = path.join(root, 'pyrightconfig.json');
    let config: Record<string, any> = {};
    if (fs.existsSync(file)) {
        try { config = JSON.parse(fs.readFileSync(file, 'utf-8')); } catch { config = {}; }
    }
    config.pythonVersion = config.pythonVersion || '3.11';
    config.typeCheckingMode = config.typeCheckingMode || 'basic';
    config.stubPath = 'typings';
    config.extraPaths = mergeUnique(config.extraPaths, ['typings', '.']);
    config.reportMissingImports = 'none';
    config.reportMissingModuleSource = 'none';
    // Older Pyright/Pylance builds reject this key ("unrecognized setting"); make
    // sure we never leave it behind from a previous version of this command.
    delete config.reportShadowedImports;
    if (suppressUndefined) {
        config.reportUndefinedVariable = 'none';
    }
    fs.writeFileSync(file, JSON.stringify(config, null, 2) + '\n', 'utf-8');
}

/** Best-effort: only touch settings.json if it's missing or parses cleanly,
 *  so we never destroy a user's commented settings file. */
function writeVscodeSettings(root: string, suppressUndefined: boolean): void {
    const dir = path.join(root, '.vscode');
    const file = path.join(dir, 'settings.json');

    let settings: Record<string, any> = {};
    if (fs.existsSync(file)) {
        const raw = fs.readFileSync(file, 'utf-8');
        try {
            settings = JSON.parse(raw);
        } catch {
            // Has comments / is invalid JSON — leave it alone, pyrightconfig.json covers us.
            return;
        }
    } else {
        fs.mkdirSync(dir, { recursive: true });
    }

    settings['python.analysis.typeCheckingMode'] = settings['python.analysis.typeCheckingMode'] || 'basic';
    settings['python.analysis.extraPaths'] = mergeUnique(settings['python.analysis.extraPaths'], ['typings', '.']);
    settings['python.analysis.stubPath'] = 'typings';
    settings['python.analysis.diagnosticSeverityOverrides'] = {
        ...(settings['python.analysis.diagnosticSeverityOverrides'] || {}),
        reportMissingModuleSource: 'none',
        reportMissingImports: 'none',
        ...(suppressUndefined ? { reportUndefinedVariable: 'none' } : {}),
    };
    fs.writeFileSync(file, JSON.stringify(settings, null, 4) + '\n', 'utf-8');
}

function mergeUnique(existing: any, additions: string[]): string[] {
    const out = Array.isArray(existing) ? existing.filter((x) => typeof x === 'string') : [];
    for (const a of additions) {
        if (!out.includes(a)) { out.push(a); }
    }
    return out;
}
