"""Jumperless MicroPython API stubs (auto-generated)"""

def connect(node1, node2, [duplicates=-1]):
    """Creates a bridge between two nodes."""
    ...

def disconnect(node1, node2):
    """Removes a specific bridge between two nodes."""
    ...

def is_connected(node1, node2):
    """Checks if a direct or indirect connection exists between two nodes."""
    ...

def nodes_clear():
    """Removes all connections from the board."""
    ...

def node(name_or_id):
    """Creates a node object from a string name or integer ID. This is useful for storing a node reference in a variable."""
    ...

def dac_set(channel, voltage, [save=True]):
    """Sets the output voltage for a specific DAC channel."""
    ...

def dac_get(channel):
    """Reads the currently set voltage for a DAC channel."""
    ...

def adc_get(channel):
    """Reads the voltage from a specific ADC channel."""
    ...

def gpio_set(pin, value):
    """Sets the output state of a GPIO pin."""
    ...

def gpio_get(pin):
    """Reads the state of a GPIO pin."""
    ...

def gpio_set_dir(pin, direction):
    """Sets the direction of a GPIO pin."""
    ...

def gpio_get_dir(pin):
    """Reads the direction of a GPIO pin."""
    ...

def gpio_set_pull(pin, pull):
    """Configures the internal pull resistor for a GPIO pin."""
    ...

def gpio_get_pull(pin):
    """Reads the pull resistor configuration of a GPIO pin."""
    ...

def gpio_set_read_floating(pin, enabled):
    """Enable or disable special floating detection when reading GPIO inputs. **These are all enabled by default.**"""
    ...

def gpio_get_read_floating(pin):
    """Returns whether floating-read detection is enabled for a GPIO pin."""
    ...

def pwm(pin, [frequency], [duty_cycle]):
    """Sets up and starts a PWM signal on a GPIO pin."""
    ...

def pwm_set_duty_cycle(pin, duty_cycle):
    """Changes the duty cycle of an existing PWM signal."""
    ...

def pwm_set_frequency(pin, frequency):
    """Changes the frequency of an existing PWM signal."""
    ...

def pwm_stop(pin):
    """Stops the PWM signal on a GPIO pin."""
    ...

def overlay_set(name, x, y, height, width, colors):
    """Creates or updates a graphic overlay."""
    ...

def overlay_clear(name):
    """Removes a specific overlay."""
    ...

def overlay_clear_all():
    """Removes ALL active overlays."""
    ...

def overlay_shift(name, dx, dy):
    """Moves an overlay by a relative offset. Wraps around edges."""
    ...

def overlay_place(name, x, y):
    """Moves an overlay to a specific absolute position. Wraps around edges."""
    ...

def overlay_set_pixel(x, y, color):
    """Sets a single pixel directly (convenience wrapper)."""
    ...

def overlay_serialize():
    """Returns the current state of all overlays as a JSON string."""
    ...

def ina_get_current(sensor):
    """Reads the current in Amps."""
    ...

def ina_get_voltage(sensor):
    """Reads the shunt voltage in Volts."""
    ...

def ina_get_bus_voltage(sensor):
    """Reads the bus voltage in Volts."""
    ...

def ina_get_power(sensor):
    """Reads the power in Watts."""
    ...

def oled_print(text, [size=-1]):
    """Displays text on the OLED screen. It can print strings, numbers, and custom Jumperless types."""
    ...

def oled_clear([show=True]):
    """Clears the OLED display."""
    ...

def oled_show():
    """Refreshes the OLED display to show the latest changes."""
    ...

def oled_connect():
    """Connects the I2C lines to the OLED display."""
    ...

def oled_disconnect():
    """Disconnects the I2C lines from the OLED display."""
    ...

def oled_set_text_size(size):
    """Set the default text size for all subsequent `oled_print()` calls."""
    ...

def oled_get_text_size():
    """Get the current default text size."""
    ...

def oled_copy_print(enable):
    """Enable or disable copying Python `print()` output to the OLED display in real-time."""
    ...

def oled_get_fonts():
    """Get a list of all available font families."""
    ...

def oled_set_font(name):
    """Set the current font family by name. The font will remain active until changed."""
    ...

def oled_get_current_font():
    """Get the name of the currently active font family."""
    ...

def oled_load_bitmap(filepath):
    """Load a bitmap file into the internal bitmap buffer."""
    ...

def oled_display_bitmap(x, y, width, height, [data=None]):
    """Display a bitmap on the OLED."""
    ...

def oled_show_bitmap_file(filepath, x, y):
    """Convenience function that loads and displays a bitmap in one call."""
    ...

def oled_get_framebuffer():
    """Get a copy of the current OLED framebuffer as a bytes object."""
    ...

def oled_set_framebuffer(data):
    """Set the entire OLED framebuffer from bytes or bytearray."""
    ...

def oled_get_framebuffer_size():
    """Get the dimensions and size of the framebuffer."""
    ...

def oled_set_pixel(x, y, color):
    """Set a single pixel on the OLED."""
    ...

def oled_get_pixel(x, y):
    """Get the color value of a single pixel."""
    ...

def probe_read([blocking=True]):
    """Reads the pad currently being touched by the probe."""
    ...

def probe_button([blocking=True], [consume=False]):
    """Reads the state of the buttons on the probe."""
    ...

def get_switch_position():
    """Gets the current probe switch position."""
    ...

def set_switch_position(position):
    """Manually sets the probe switch position."""
    ...

def check_switch_position():
    """Checks the probe switch position using current sensing and updates the internal state."""
    ...

def probe_autoconnect([enable]):
    """Gets or sets whether the probe DAC auto-connects on the routable buffer."""
    ...

def clickwheel_get_position():
    """Gets the raw clickwheel position counter."""
    ...

def clickwheel_reset_position():
    """Resets the clickwheel position counter to 0."""
    ...

def clickwheel_get_direction([consume=True]):
    """Gets the current clickwheel direction event."""
    ...

def clickwheel_get_button():
    """Gets the current clickwheel button state."""
    ...

def get_net_name(netNum):
    """Gets the name of a specific net."""
    ...

def set_net_name(netNum, name):
    """Sets a custom name for a net."""
    ...

def get_net_color(netNum):
    """Gets the color of a net as a 32-bit RGB value."""
    ...

def get_net_color_name(netNum):
    """Gets the color name of a net as a human-readable string."""
    ...

def set_net_color(netNum, color, [r], [g], [b]):
    """Sets the color of a net by name, hex string, or RGB values."""
    ...

def set_net_color_hsv(netNum, h, [s], [v]):
    """Sets the color of a net using HSV (Hue, Saturation, Value) color space. Automatically detects whether you're using normalized (0.0-1.0) or full-range (0-255) values based on the hue parameter."""
    ...

def get_num_nets():
    """Gets the number of currently active nets."""
    ...

def get_num_bridges():
    """Gets the total number of bridges (connections)."""
    ...

def get_net_nodes(netNum):
    """Gets all nodes in a net as a comma-separated string."""
    ...

def get_bridge(bridgeIdx):
    """Gets information about a specific bridge."""
    ...

def get_net_info(netNum):
    """Gets comprehensive information about a net as a dictionary."""
    ...

def get_num_paths([include_duplicates=True]):
    """Gets the number of routing paths currently in use."""
    ...

def get_path_info(path_idx):
    """Gets detailed information about a specific routing path."""
    ...

def get_all_paths():
    """Gets all routing paths as a list of dictionaries."""
    ...

def get_path_between(node1, node2):
    """Queries the routing path between two specific nodes."""
    ...

def pin.value([val]):
    """For INPUT: Reads the current pin state (0 or 1)."""
    ...

def arduino_reset():
    """Resets the connected Arduino Nano."""
    ...

def run_app(appName):
    """Launches a built-in Jumperless application."""
    ...

def pause_core2(pause):
    """Pauses or resumes core2 processing."""
    ...

def send_raw(chip, x, y, setOrClear):
    """Sends raw data to core2 for direct chip control."""
    ...

def change_terminal_color(color, [flush=True]):
    """Sets the terminal text color using 256-color ANSI codes."""
    ...

def cycle_term_color([reset=False], [step=1.0], [flush=True]):
    """Cycles through the terminal color palette."""
    ...

def force_service(name):
    """Forces immediate execution of a specific system service by name."""
    ...

def force_service_by_index(index):
    """Forces immediate execution of a specific system service by index (faster than name lookup)."""
    ...

def get_service_index(name):
    """Gets the index of a service by name for use with `force_service_by_index()`."""
    ...

def switch_slot(slot):
    """Switches to a different connection slot."""
    ...

def context_toggle():
    """Toggles the connection context between `global` and `python` modes."""
    ...

def context_get():
    """Gets the current connection context name."""
    ...

def get_state():
    """Returns the entire board state as a formatted JSON string. This includes nets, power settings, and GPIO configuration."""
    ...

def set_state(json, [clear_first=True], [from_wokwi=False]):
    """Applies a board state from a JSON string or, if ``from_wokwi`` is True, from a"""
    ...

def help():
    """Displays a comprehensive list of all available functions and constants in the `jumperless` module."""
    ...

def nodes_help():
    """Displays a detailed reference for all available node names and their aliases."""
    ...

# Constants
TOP_RAIL: int = ...
T_RAIL: int = ...
BOTTOM_RAIL: int = ...
BOT_RAIL: int = ...
B_RAIL: int = ...
GND: int = ...
DAC0: int = ...
DAC_0: int = ...
DAC1: int = ...
DAC_1: int = ...
ADC0: int = ...
ADC1: int = ...
ADC2: int = ...
ADC3: int = ...
ADC4: int = ...
PROBE: int = ...
UART_TX: int = ...
TX: int = ...
UART_RX: int = ...
RX: int = ...
GPIO_1: int = ...
GPIO_2: int = ...
GPIO_3: int = ...
GPIO_4: int = ...
GPIO_5: int = ...
GPIO_6: int = ...
GPIO_7: int = ...
GPIO_8: int = ...
HIGH: int = ...
LOW: int = ...
FLOATING: int = ...
INPUT: int = ...
OUTPUT: int = ...
D0: int = ...
D1: int = ...
D2: int = ...
D3: int = ...
D4: int = ...
D5: int = ...
D6: int = ...
D7: int = ...
D8: int = ...
D9: int = ...
D10: int = ...
D11: int = ...
D12: int = ...
D13: int = ...
A0: int = ...
A1: int = ...
A2: int = ...
A3: int = ...
A4: int = ...
A5: int = ...
A6: int = ...
A7: int = ...
SINE: int = ...
TRIANGLE: int = ...
SAWTOOTH: int = ...
SQUARE: int = ...
RAMP: int = ...
ARBITRARY: int = ...
